# Pandas for AI/ML – Conceptual & Technical Assessment

**Name:** Bodavula Venkata Ajay Kumar

### Section A output prediction 
#### Q1: Array operations and vectorization

In [16]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30])
s = pd.Series([10, 20, 30])

print(arr * 2)
print(s * 2)

[20 40 60]
0    20
1    40
2    60
dtype: int64



- **Predicted Output:**
  
  [20 40 60]
  0    20
  1    40
  2    60
  dtype: int64

- **Explanation:**
 
  - **Similarity:** Both NumPy arrays and Pandas Series perform element-wise vectorized multiplication when multiplied by a scalar.
 
  - **Difference:** A Pandas Series maintains explicit index labels (`0, 1, 2`) alongside data values, whereas a NumPy array contains only raw numerical values without axis labels.

###  Q2: Boolean Filtering

In [17]:
import pandas as pd

df = pd.DataFrame({
    'Student': ['A', 'B', 'C', 'D'],
    'Marks': [45, 80, 65, 90]
})

result = df[df['Marks'] >= 65]
print(result[['Student', 'Marks']])

  Student  Marks
1       B     80
2       C     65
3       D     90



- **Predicted Output:**

    Student  Marks
  1       B     80
  2       C     65
  3       D     90

- **Explanation:**

  The condition `df['Marks'] >= 65` filters rows for students B, C, and D. The resulting DataFrame contains **3 rows and 2 columns**.

###  Q3: Descriptive statistics

In [18]:
import pandas as pd

df = pd.DataFrame({
    'Marks': [10, 20, 30, 40, 50]
})

print(df['Marks'].mean())
print(df['Marks'].max())
print(df['Marks'].median())

30.0
50
30.0



- **Predicted Output:**

  30.0

  50
  
  30.0

- **Explanation:**

  The mean calculates the arithmetic average of all values (`30.0`), max returns the highest value (`50`), and median identifies the exact middle value (`30.0`). Unlike the mean, the median is resilient against extreme dataset outliers.

###  Q4: Group-wise Analysis

In [19]:
import pandas as pd

df = pd.DataFrame({
    'Department': ['IT', 'HR', 'IT', 'HR'],
    'Salary': [40000, 30000, 60000, 50000]
})

print(df.groupby('Department')['Salary'].mean())

Department
HR    40000.0
IT    50000.0
Name: Salary, dtype: float64



- **Predicted Output:**

  Department

  HR    40000.0

  IT    50000.0
  
  Name: Salary, dtype: float64

- **Explanation:**

  `df.groupby('Department')` splits data into department groups, calculates the average salary per department (HR: `(30000+50000)/2 = 40000.0`, IT: `(40000+60000)/2 = 50000.0`), and returns the aggregated mean indexed by department.

###  Q5: Pandas Correlation - Positive

In [20]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

print(df['Hours'].corr(df['Marks']))

1.0



- **Predicted Output:** 

  1.0

- **Explanation:**

  The coefficient `1.0` indicates a perfect positive linear correlation[cite: 1], meaning marks increase in direct linear proportion to study hours[cite: 1].

###  Q6: Pandas Correlation - Negative

In [21]:
import pandas as pd

df = pd.DataFrame({
    'Price': [10, 20, 30, 40],
    'Demand': [100, 80, 60, 40]
})

print(df['Price'].corr(df['Demand']))

-1.0



- **Predicted Output:** 

  -1.0

- **Explanation:**

  The negative sign (`-1.0`) indicates a perfect inverse linear relationship[cite: 1], showing that demand drops in direct proportion as price increases[cite: 1].

### Section B - code correction
#### Q1: JSON and CSV
- **Error Identified:** `header=None` prevents Pandas from treating the top row as column headers[cite: 1], causing data values to be incorrectly assigned as column labels[cite: 1].
- **Correction:** Removed `header=None` so Pandas automatically parses the first row as headers[cite: 1].

In [ ]:
import pandas as pd

# Corrected code
df = pd.read_csv("student_performance.csv", header=0)
print(df)

    Student_ID     Name  Age  Gender    Department  Attendance  Study_Hours  \
0         1001     Ravi   21  Female  Data Science        84.0          5.5   
1         1002    Priya   23    Male         Cloud        76.1          8.4   
2         1003     Arun   23  Female        Python        98.9          2.0   
3         1004    Meena   21    Male  Data Science        97.9          3.6   
4         1005    Kiran   22    Male            AI         NaN          2.8   
..         ...      ...  ...     ...           ...         ...          ...   
56        1057   Venkat   22    Male            AI        91.2          2.5   
57        1058  Sahithi   23    Male            AI        97.5          2.4   
58        1059    Akash   21    Male            AI        78.3          8.3   
59        1060  Madhavi   20    Male            AI        85.1          6.5   
60        1012    Manoj   21    Male         Cloud        80.5          2.0   

    Assignment_Score  Exam_Score           City Enr

###  Q2: Data Analysis
- **Error Identified:** 
`sort_values('Salary')` defaults to ascending order (`ascending=True`), which displays the five lowest salaries instead of the five highest.
- **Correction:

     ** Added `ascending=False` to sort salaries in descending order before extracting `.head(5)`[cite: 1].
-  **One-line Explanation:

       ** Adding `ascending=False` sorts the salaries from highest to lowest so that `head(5)` retrieves the five highest salaries[cite: 1].

In [23]:
import pandas as pd

df = pd.DataFrame({
    'Employee': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Salary': [30000, 50000, 25000, 60000, 45000, 70000]
})

# Corrected code
print(df.sort_values('Salary', ascending=False).head(5))

  Employee  Salary
5        F   70000
3        D   60000
1        B   50000
4        E   45000
0        A   30000


###  Q3: Cleaning Data
- **Error Identified:

      ** `df['Marks'].fillna()` returns a modified copy of the Series by default[cite: 1], which leaves the original DataFrame column unchanged[cite: 1].
- **Correction:

      ** Reassigned the result back to `df['Marks']` to persist the filled mean values in the DataFrame[cite: 1].
- **One-line Explanation:

      ** Reassigning `df['Marks'] = df['Marks'].fillna(...)` ensures the filled missing values update the original DataFrame column[cite: 1].

In [24]:
import pandas as pd

df = pd.DataFrame({'Marks': [70, None, 90]})

# Corrected code
df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df)

   Marks
0   70.0
1   80.0
2   90.0


###  Q4: Correlation
- **Error Identified:

      ** `df.corr('Hours', 'Marks')` passes invalid column string arguments to `DataFrame.corr()`[cite: 1], which expects matrix method parameters like `'pearson'` or `'spearman'`[cite: 1].
- **Correction:

     ** Used the Series correlation syntax `df['Hours'].corr(df['Marks'])` to compute pairwise correlation between the two specific columns[cite: 1].
- **One-line Explanation:

     ** Using `df['Hours'].corr(df['Marks'])` correctly calculates the pairwise correlation coefficient between two Pandas Series[cite: 1].

In [25]:
import pandas as pd

df = pd.DataFrame({
    'Hours': [1, 2, 3, 4],
    'Marks': [20, 40, 60, 80]
})

# Corrected code
print(df['Hours'].corr(df['Marks']))

1.0


### Section C - Edge cases
#### Q1: Array Shapes and Broadcasting


-

In [28]:
import numpy as np

# Creating a column array with 3 values
a = np.array([[10], [20], [30]])

# Creating a row array with 3 values
b = np.array([[1, 2, 3]])

# NumPy broadcasts the arrays and performs addition
result = a + b

print(result)
print(result.shape)

[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)


**Answer:**

The output is:

```text
[[11 12 13]
 [21 22 23]
 [31 32 33]]
(3, 3)
```

The shape of `a` is `(3, 1)` and the shape of `b` is `(1, 3)`. After broadcasting, both arrays are treated as compatible with shape `(3, 3)`, so the result also has shape `(3, 3)`.

**Explanation:**
Broadcasting allows NumPy to perform operations on arrays with different shapes by automatically expanding their dimensions when they are compatible. Here, each value in `a` is added to all three values in `b`.

If `b = np.array([1, 2])`, broadcasting would not work because the dimensions are not compatible for this operation.


###  Q2: Handling CSV Parsing Issues

In [29]:
import pandas as pd

# Reading the CSV file
df = pd.read_csv("student_performance.csv")

# Displaying the data
print(df)

# Checking the data types of each column
print(df.dtypes)

    Student_ID     Name  Age  Gender    Department  Attendance  Study_Hours  \
0         1001     Ravi   21  Female  Data Science        84.0          5.5   
1         1002    Priya   23    Male         Cloud        76.1          8.4   
2         1003     Arun   23  Female        Python        98.9          2.0   
3         1004    Meena   21    Male  Data Science        97.9          3.6   
4         1005    Kiran   22    Male            AI         NaN          2.8   
..         ...      ...  ...     ...           ...         ...          ...   
56        1057   Venkat   22    Male            AI        91.2          2.5   
57        1058  Sahithi   23    Male            AI        97.5          2.4   
58        1059    Akash   21    Male            AI        78.3          8.3   
59        1060  Madhavi   20    Male            AI        85.1          6.5   
60        1012    Manoj   21    Male         Cloud        80.5          2.0   

    Assignment_Score  Exam_Score           City Enr

**Answer:**

The CSV file was successfully read using `pd.read_csv()`.

**Output:**
The DataFrame contains **61 rows and 13 columns**.

**Important observations:**

* The `Name` column is stored as `object`, which is suitable for names.
* The `Attendance` column is `float64` because it contains a missing value (`NaN`).
* The `Enrollment_Date` column is currently `object`, so it has not been converted to a proper date format.
* Missing values should be handled carefully instead of automatically treating every missing value as the same type of problem.

**Explanation:**
`pd.read_csv()` correctly reads the CSV data into a DataFrame. The `dtypes` output helps us understand the data type of each column and identify columns that may need further cleaning, such as `Enrollment_Date`.


### Q3. Salary Extreme

In [30]:
import pandas as pd

# Creating a salary column with one extremely high value
df = pd.DataFrame({
    'Salary': [25000, 30000, 35000, 10000000]
})

# Calculating the mean salary
print("Mean:", df['Salary'].mean())

# Calculating the median salary
print("Median:", df['Salary'].median())

# Finding the highest salary
print("Highest Salary:", df['Salary'].max())

Mean: 2522500.0
Median: 32500.0
Highest Salary: 10000000


**Answer:**

**Output:**

```text
Mean: 2522500.0
Median: 32500.0
Highest Salary: 10000000
```

**Explanation:**

The mean salary is `2,522,500.0`, while the median salary is `32,500.0`.

The salary of `10,000,000` is an extreme value, so it increases the mean significantly. The median is less affected by this extreme value and therefore represents the typical salary better in this example.

The highest salary should be investigated before removing it. It could be a genuine salary or it could be an incorrect data entry. We should not remove it without checking the original data.

### Section D – Scenario-Based Questions

#### Q1. Student Assessment Data Cleaning Pipeline

**Scenario:
    
    
      **A student assessment dataset contains missing marks, duplicate student records, inconsistent department names such as `IT`, `it`, and `I.T.`, and marks stored as text[cite: 1, 3]. Develop a cleaning sequence to standardize the data, handle missing values, remove duplicates, and convert marks into a suitable numeric type[cite: 1, 3]. State one risk of deleting missing values without investigating why they are missing[cite: 1, 3].

**Dataset:
    ** `student_assessment_dirty.csv`[cite: 1, 3]

### 1. Load the CSV file and inspect the dataset using head(), info(), and isnull().sum()

Loading `student_assessment_dirty.csv` and reviewing structural information, data types, and initial missing value counts across all columns.

In [38]:
import io
import pandas as pd

# Creating in-memory dataset matching student_assessment_dirty.csv
csv_data = """Student_ID,Student_Name,Department,Assessment,Marks
S101,Asha,IT,Python,85
S102,Ravi,it,Python,78
S103,Neha,I.T.,Python,92
S104,Karan,HR,Python,
S105,Meera,HR,Python,Absent
S106,Arjun,Finance,Python,0
S107,Priya,finance,Python,67
S108,Rahul,IT,Python,75
S102,Ravi,it,Python,78
S109,Sneha,I.T.,Python,NA
S110,Varun,HR,Python,88 marks
S111,Diya,Finance,Python,91
S112,Aman,IT,Python,
S113,Nisha,HR,Python,64
S114,Kabir,Finance,Python,105"""

# To load directly from a file, replace io.StringIO with "student_assessment_dirty.csv"
df = pd.read_csv(io.StringIO(csv_data))

print("--- Head (First 5 Rows) ---")
print(df.head())

print("\n--- Info ---")
print(df.info())

print("\n--- Missing Values Count ---")
print(df.isnull().sum())

--- Head (First 5 Rows) ---
  Student_ID Student_Name Department Assessment   Marks
0       S101         Asha         IT     Python      85
1       S102         Ravi         it     Python      78
2       S103         Neha       I.T.     Python      92
3       S104        Karan         HR     Python     NaN
4       S105        Meera         HR     Python  Absent

--- Info ---
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Student_ID    15 non-null     str  
 1   Student_Name  15 non-null     str  
 2   Department    15 non-null     str  
 3   Assessment    15 non-null     str  
 4   Marks         12 non-null     str  
dtypes: str(5)
memory usage: 732.0 bytes
None

--- Missing Values Count ---
Student_ID      0
Student_Name    0
Department      0
Assessment      0
Marks           3
dtype: int64


### 2. Standardize department names so that IT, it, and I.T. are represented consistently. Apply the same approach to Finance.

Cleaning whitespace and replacing inconsistent department entries (`it`, `I.T.` $\rightarrow$ `IT` and `finance` $\rightarrow$ `Finance`) to unify categories for aggregation.

In [39]:
# Clean and replace department variations
df["Department"] = (
    df["Department"]
    .str.strip()
    .replace(
        {
            "it": "IT",
            "I.T.": "IT",
            "finance": "Finance",
            "hr": "HR",
        }
    )
)

print("Unique Departments after standardization:")
print(df["Department"].unique())

Unique Departments after standardization:
<StringArray>
['IT', 'HR', 'Finance']
Length: 3, dtype: str


### 3. Identify and remove exact duplicate student assessment records.

Identifying exact repeated records across all columns and dropping duplicate entries.

In [40]:
initial_count = len(df)

# Remove exact duplicate rows
df = df.drop_duplicates()

duplicates_removed = initial_count - len(df)
print(f"Number of duplicate records removed: {duplicates_removed}")

Number of duplicate records removed: 1


### 4. Convert the Marks column into a numeric format, handling "88 marks", "Absent", "NA", and blank entries appropriately.

Extracting digits from text strings like `'88 marks'`, setting `'Absent'` students to a mark of `0`, and coercing invalid or blank entries (`'NA'`, empty strings) to Pandas `NaN`.

In [41]:
# Convert to string and strip spaces
df["Marks"] = df["Marks"].astype(str).str.strip()

# Convert 'Absent' status to 0
df.loc[df["Marks"].str.lower() == "absent", "Marks"] = "0"

# Extract numeric digits from text such as '88 marks'
df["Marks"] = df["Marks"].str.extract(r"(\d+)")[0]

# Convert column to float numeric data type
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

print("Marks column data type:", df["Marks"].dtype)

Marks column data type: float64


### 5. Investigate missing marks and distinguish absent students from students whose marks have not been entered. State one risk of deleting missing values without investigating why they are missing.

* **Distinction:   
     ** An `'Absent'` entry represents an active student who took zero marks, whereas a blank   or `'NA'` entry represents unrecorded data that requires administrative follow-up or imputation.
* **Risk of Deleting Missing Values:
     ** Deleting missing values directly introduces selection bias into the dataset, distorts descriptive statistics like the mean and median, and permanently removes valid student metadata.

In [42]:
# Distinguish absent students (mark = 0) from unrecorded missing marks (NaN)
absent_students = df[df["Marks"] == 0]
missing_marks_students = df[df["Marks"].isnull()]

print("--- Absent Students (Marks = 0) ---")
print(absent_students[["Student_ID", "Student_Name", "Department", "Marks"]])

print("\n--- Unrecorded / Missing Marks (NaN) ---")
print(missing_marks_students[["Student_ID", "Student_Name", "Department", "Marks"]])

--- Absent Students (Marks = 0) ---
  Student_ID Student_Name Department  Marks
4       S105        Meera         HR    0.0
5       S106        Arjun    Finance    0.0

--- Unrecorded / Missing Marks (NaN) ---
   Student_ID Student_Name Department  Marks
3        S104        Karan         HR    NaN
9        S109        Sneha         IT    NaN
12       S112         Aman         IT    NaN


### 6. Identify marks outside the valid range of 0–100 and decide how they should be handled.

Marks outside $[0, 100]$ (such as `105` for `S114 Kabir`) represent data entry errors. They are flagged and replaced with `NaN` so they do not distort final statistical evaluations.

In [43]:
# Find out-of-range marks (< 0 or > 100)
invalid_marks_mask = (df["Marks"] < 0) | (df["Marks"] > 100)
invalid_marks_count = invalid_marks_mask.sum()

# Convert out-of-range marks to NaN
df.loc[invalid_marks_mask, "Marks"] = None

print(f"Number of invalid marks identified and converted to NaN: {invalid_marks_count}")

Number of invalid marks identified and converted to NaN: 1


### 7. Display the cleaned DataFrame and report the number of records removed, missing marks remaining, and invalid marks identified.

Final dataset view along with the final data cleaning summary report.

In [44]:
# Calculate total remaining missing marks
missing_marks_remaining = df["Marks"].isnull().sum()

print("--- Cleaned DataFrame ---")
print(df)

print("\n--- Data Cleaning Summary Report ---")
print(f"1. Number of duplicate records removed: {duplicates_removed}")
print(f"2. Number of invalid marks identified (>100 or <0): {invalid_marks_count}")
print(f"3. Number of missing marks remaining (NaN): {missing_marks_remaining}")

--- Cleaned DataFrame ---
   Student_ID Student_Name Department Assessment  Marks
0        S101         Asha         IT     Python   85.0
1        S102         Ravi         IT     Python   78.0
2        S103         Neha         IT     Python   92.0
3        S104        Karan         HR     Python    NaN
4        S105        Meera         HR     Python    0.0
5        S106        Arjun    Finance     Python    0.0
6        S107        Priya    Finance     Python   67.0
7        S108        Rahul         IT     Python   75.0
9        S109        Sneha         IT     Python    NaN
10       S110        Varun         HR     Python   88.0
11       S111         Diya    Finance     Python   91.0
12       S112         Aman         IT     Python    NaN
13       S113        Nisha         HR     Python   64.0
14       S114        Kabir    Finance     Python    NaN

--- Data Cleaning Summary Report ---
1. Number of duplicate records removed: 1
2. Number of invalid marks identified (>100 or <0): 1
